os: windows
language: sh
python: "3.7"
before_install:
  - choco install python3
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  - python -m pip install --upgrade pip wheel
install:
  - pip install pywin32
  - pip install -r requirements.txt
script:
  - echo "Hello World!"
